JuniorIS Project
Luca Napora

Frameworks:
* OpenGl
* libGlew.2.2.0
* libglfw.3.3

This project was written in Xcode, and from my understanding Xcode does not use the typical makefiles you see in other IDEs. To run this project, you need to incorporate the following packages:

The instructions to download OpenGl can be found here: https://www.opengl.org/

Instructions to download glfw: https://www.glfw.org/download.html
    *I used Cmake when downloading glfw

Instructions to download GLAD: https://glad.dav1d.de/

I used the tutorial from learnopengl to build these packages: https://learnopengl.com/Getting-started/Creating-a-window

Because of problems with github, this project resides on the branch learndemo instead of the main branch of my repository.

Much of this project relied on the use of two OpenGl tutorials: https://learnopengl.com and http://www.opengl-tutorial.org/
This tutorials especially helped with:
    *Building and creating an opengl window
    *Incorporating shaders written in glsl into my project
    *Creating a render loop
    *Creating the vertices needed for the cube
    *Using VBOs and VOAs
    
Most of the unique coding that I did was in relation to the implementation of lighting. The base of the project was heavily reliant on these respective guides.

To change from the Phong Shader Model to the Gouraud Shader Model:
    *There are two instances of both the vertex shader and the fragment shader, one for the Phong Model and one for the Gouraud Model
    *To change to the Gouraud Model, simply comment out the phong vertex shader and the phong fragment shader and uncomment the Gouraud vertex shader and the gouraud fragment shader


